### ISSUE TITLE
Shopland Pro - QA checklist

### ISSUE THREAD

**Issue by NinoLopezTech** [NinoLopezTech/Programming-Fundamentals-in-JavaScript#1]
- [ ] 1. SEED close confirmation modal. We will enable a SEED option that allows the modal to only pop up during gameplay, warning the user that their current progress will not be saved. The popup should not appear anywhere else in the game (e.g., a feedback screen).

- [ ] 2. Layouts on iPhone X.

- [ ] 3. QSP API changes across all SEED supported browsers and devices.  

- [ ] 4. QA that response images are being called in from QSP.

- [ ] 5. QA if Game XP’s are being awarded upon app completion.
